#!/usr/bin/env bash
# Build the generated assets of the web viewer (issue 15).
#
#   web/gedlint-wasm.js  the engine (wasm32 cdylib), base64-embedded in a
#                        same-origin script. The page ships a CSP with
#                        connect-src 'none', so the .wasm can never be
#                        fetched: it has to arrive as script bytes.
#   web/example.js       the broken sample tree, base64-embedded for the
#                        same reason (the "Try an example" button must not
#                        hit the network either).
#
# Usage: scripts/build-web.sh [path-to-gedlint.wasm]
# Default path is the cdylib from
#   cargo build --release --target wasm32-unknown-unknown --lib
# (--lib is load-bearing: the bin target writes the same filename and would
# overwrite it with the CLI wrapper, which is not a valid module for the page.)
#
# base64 wraps at 76 columns on macOS and not at all on GNU coreutils;
# tr -d '\n' normalizes both.
set -euo pipefail
cd "$(dirname "$0")/.."

WASM=${1:-target/wasm32-unknown-unknown/release/gedlint.wasm}
if [ ! -f "$WASM" ]; then
  echo "missing $WASM" >&2
  echo "build it first: cargo build --release --target wasm32-unknown-unknown --lib" >&2
  exit 1
fi
if [ ! -f web/example.ged ]; then
  echo "missing web/example.ged" >&2
  exit 1
fi

{
  echo "// Generated by scripts/build-web.sh; do not edit."
  echo "// Base64 of the wasm32-unknown-unknown cdylib. Kept as a script so the"
  echo "// page never fetches the module: its CSP forbids every connection."
  echo "const GEDLINT_WASM_B64 = \"$(base64 < "$WASM" | tr -d '\n')\";"
} > web/gedlint-wasm.js

{
  echo "// Generated by scripts/build-web.sh from web/example.ged; do not edit."
  echo "const EXAMPLE_GED_B64 = \"$(base64 < web/example.ged | tr -d '\n')\";"
} > web/example.js

echo "web/gedlint-wasm.js: $(wc -c < web/gedlint-wasm.js) bytes"
echo "web/example.js:      $(wc -c < web/example.js) bytes"
