#!/usr/bin/env bash
# Regenerates CHANGELOG.md from the GitHub Releases of this repo.
#
# The releases are the source of truth: their notes are produced by
# `gh release create --generate-notes`, so the changelog is a view of what
# actually shipped rather than a second list somebody has to remember to
# update. Never edit CHANGELOG.md by hand; run this instead.
#
#   scripts/changelog.sh          # rewrite CHANGELOG.md
#   scripts/changelog.sh --check  # fail if it is out of date (for CI)
set -euo pipefail
cd "$(dirname "$0")/.."

out=$(
  printf '# Changelog\n\nGenerated by `scripts/changelog.sh` from the GitHub Releases. Do not edit by hand.\n'
  gh api --paginate 'repos/{owner}/{repo}/releases' \
    --jq '.[]
          | select(.draft | not)
          # Skip moving major tags such as v1: they are aliases for whichever
          # version is current, not releases of their own, and they would sort
          # to the top carrying the date they were first created.
          | select(.tag_name | test("^v[0-9]+$") | not)
          | "\n## \(.tag_name) — \(.published_at[0:10])\n\n\(.body // "No notes." | rtrimstr("\n"))\n"'
)

if [ "${1:-}" = "--check" ]; then
  if ! diff -q <(printf '%s\n' "$out") CHANGELOG.md >/dev/null 2>&1; then
    echo "CHANGELOG.md is out of date; run scripts/changelog.sh" >&2
    exit 1
  fi
  echo "CHANGELOG.md is up to date"
else
  printf '%s\n' "$out" > CHANGELOG.md
  echo "wrote CHANGELOG.md ($(wc -l < CHANGELOG.md | tr -d ' ') lines)"
fi
